---
- name: Include variables suitable to our OS Family
  include_vars: "{{ ansible_os_family }}.yml"

- name: mounts
  mount:
    name: "{{ item.key }}"
    src: "{{ item.value.src }}"
    fstype: "{{ item.value.fstype }}"
    opts: "{{ item.value.opts }}"
    state: "{{ item.value.state }}"
  with_dict: "{{ mount_points }}"
